### PR TITLE
Change healthcheck method

### LINKED ISSUE #5: Nginx container is "unhealthy" if add the file "vhost-overrides.conf".
I added the configuration file `vhost-overrides.conf` (according to https://github.com/docksal/service-nginx#configuration-overrides):

```
location ~ \.txt$ {
  allow all;
  access_log off;
  log_not_found off;
  try_files $uri $uri/ /index.php?$query_string;
}
```
and now I have this problem:
```
$ fin p reset nginx
Killing myproject_nginx_1 ... done
Going to remove myproject_nginx_1
Removing myproject_nginx_1 ... done
Starting services...
myproject_backstop_1 is up-to-date
myproject_db_1 is up-to-date
myproject_cli_1 is up-to-date
myproject_mail_1 is up-to-date
myproject_browser_1 is up-to-date
Creating myproject_nginx_1 ... done
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
Waiting for project stack to become ready...
 ERROR:  Project heathcheck has timed out
        One or more containers did not enter a healthy state within 60 seconds of the project start.
        See fin project status for details
        Check fin logs for more details

$ fin logs nginx
Attaching to myproject_nginx_1
nginx_1     | /usr/local/bin/docker-entrypoint.sh: running /etc/docker-entrypoint.d/05-config-templates.sh
nginx_1     | /usr/local/bin/docker-entrypoint.sh: running /etc/docker-entrypoint.d/06-basic-auth.sh
nginx_1     | /usr/local/bin/docker-entrypoint.sh: running /etc/docker-entrypoint.d/07-user-overrides.sh
nginx_1     | Including configuration overrides from /var/www/.docksal/etc/nginx/vhost-overrides.conf
nginx_1     | Including configuration overrides from /var/www/.docksal/etc/nginx/vhosts.conf
nginx_1     | /usr/local/bin/docker-entrypoint.sh: running /etc/docker-entrypoint.d/10-docker-cmd.sh
nginx_1     | 2019-08-30 16:44:19 | Passing execution to: nginx -g daemon off;
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:44:22 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:44:27 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:44:32 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:44:37 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:44:42 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:44:48 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:44:53 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:44:58 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:45:03 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:45:08 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:45:13 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:45:19 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:45:24 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:45:29 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:45:34 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"
nginx_1     | 127.0.0.1 - - [30/Aug/2019:16:45:39 +0000] "GET /.healthz HTTP/1.1" 403 169 "-" "Wget" "-"

$ fin p status
      Name                    Command                   State                    Ports             
---------------------------------------------------------------------------------------------------
myproject_backstop_1   top -b                           Up                                             
myproject_browser_1    /opt/bin/entry_point.sh          Up               4444/tcp                      
myproject_cli_1        /opt/startup.sh supervisord      Up (healthy)     0.0.0.0:2023->22/tcp, 9000/tcp
myproject_db_1         docker-entrypoint.sh mysqld      Up (healthy)     0.0.0.0:32800->3306/tcp       
myproject_mail_1       MailHog                          Up               1025/tcp, 80/tcp, 8025/tcp    
myproject_nginx_1      docker-entrypoint.sh nginx ...   Up (unhealthy)   443/tcp, 80/tcp               

$ fin -v
1.86.2

$ docker -v
Docker version 19.03.1, build 74b1e89
```

How to set local settings correctly?

### PR DESCRIPTION
**Pull request by sergey-zabolotny**
Fixes: https://github.com/docksal/service-nginx/issues/5

### CODE REVIEW

**Comment by lmakarov** [comment]
The healthcheck should also verify that nginx config is valid.
See https://github.com/docksal/service-vhost-proxy/blob/develop/healthcheck.sh#L6-L8

Preferably, the `/.healthz` endpoint should be there. If a custom config breaks it, then there must be an issue in the custom config and it needs to be revised.

**Comment by achekulaev** [comment]
@lmakarov #5 shows that config can just deny access to `/.healthz` and be perfectly valid. Inaccessible `/.healthz` cannot be a way to check config.

**Comment by lmakarov** [comment]
@achekulaev I don't see how the config snippet in #5 can affect the `/.healthz` endpoint:

```
location ~ \.txt$ {
  allow all;
  access_log off;
  log_not_found off;
  try_files $uri $uri/ /index.php?$query_string;
}
```

There may be a totally different issue with how config overrides are handled.

**Comment by sergey-zabolotny** [comment]
by default we use https://github.com/docksal/service-nginx/blob/develop/conf/includes/defaults.conf.tmpl as config (here configured `/.healthz` location), but when user has  `/var/www/.docksal/etc/nginx/vhost-overrides.conf` file https://github.com/docksal/service-nginx/blob/develop/docker-entrypoint.d/07-user-overrides.sh#L17 overwrite default.conf with user configuration. in this case we do not have configuration for `/.healthz` location

I had an idea to put `/.healthz` location config into the server block, but unfortunately location directive cannot be used inside server block

**Comment by lmakarov** [comment]
Had a discussion with @sergey-zabolotny. We agreed that the proposed approach is good. The nginx config validation is already there, which I did not notice initially.

**Pull request merged**
